// <auto-generated />
using CampeonatoFut.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CampeonatoFut.Migrations
{
    [DbContext(typeof(TabelaContext))]
    [Migration("20211121071953_TbBrasileiro")]
    partial class TbBrasileiro
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("CampeonatoFut.Models.Tabela", b =>
                {
                    b.Property<int>("IdCampeonato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Derrotas")
                        .HasColumnType("int");

                    b.Property<int>("Empates")
                        .HasColumnType("int");

                    b.Property<int>("GolsFeitos")
                        .HasColumnType("int");

                    b.Property<int>("GolsSofridos")
                        .HasColumnType("int");

                    b.Property<int>("IdTime")
                        .HasColumnType("int");

                    b.Property<int>("SaldodeGols")
                        .HasColumnType("int");

                    b.Property<string>("Times")
                        .HasColumnType("nvarchar(max)");
                    
                    b.Property<string>("Pontos")
                       .HasColumnType("int");

                    b.Property<int>("Vencidos")
                        .HasColumnType("int");

                    b.HasKey("IdCampeonato");

                    b.ToTable("Tabelas");
                });
#pragma warning restore 612, 618
        }
    }
}
